import Head from "next/head";
import { useEffect, useState } from "react";
import { Inter } from "@next/font/google";
import { ImNewTab, ImSearch } from "react-icons/im";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [link, setLink] = useState("");
  const [metadata, setMetadata] = useState<any>(null);
  const [video, setVideo] = useState<any>(null);
  const [audio, setAudio] = useState<any>(null);
  const [allFormats, setAllFormats] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [updateVideo, setUpdateVideo] = useState(0);
  const [quality, setQuality] = useState("");

  let qualities: any = [];

  const getVideo = () => {
    qualities = [];
    setMetadata(null);
    setVideo(null);
    setAudio(null);
    setAllFormats(null);
    setLoading(true);
    fetch("/api/getVideo", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ url: link }),
    })
      .then((res) => res.json())
      .then((data) => {
        setLoading(false);
        console.log(data);

        setMetadata(data.response.videoDetails);
        setAllFormats(data.response.streamingData.adaptiveFormats);
        const defaultVideo = data.response.streamingData.adaptiveFormats.find(
          (format: any) => {
            return format.mimeType.includes("video/mp4");
          }
        );
        setVideo(defaultVideo);
        setQuality(defaultVideo.qualityLabel);
        setAudio(
          data.response.streamingData.adaptiveFormats.find((format: any) => {
            return format.mimeType.includes("audio/mp4");
          })
        );
      })
      .catch((err) => {
        console.log("error", err);
      });
  };

  console.log("video", video, video?.qualityLabel);

  useEffect(() => {
    setVideo(
      allFormats?.find(
        (format: any) =>
          format.mimeType.includes("video/mp4") &&
          format.qualityLabel == quality
      )
    );
  }, [updateVideo]);

  const parseSeconds = (d: number) => {
    const h = String(Math.floor(d / 3600)).padStart(2, "0");
    const m = String(Math.floor((d % 3600) / 60)).padStart(2, "0");
    const s = String(Math.floor((d % 3600) % 60)).padStart(2, "0");
    return `${h}:${m}:${s}`;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen min-h-screen flex flex-col items-center justify-center bg-[url('/background.png')] bg-cover bg-center px-5 md:px-16 lg:px-32 py-32">
        <h1 className="text-7xl font-bold gradient-red text-transparent !bg-clip-text uppercase text-center">
          YouTube Downloader
        </h1>
        <h2 className="text-2xl font-medium text-white text-center">
          Download any YouTube video in video (mp4) or audio (m4a) format!
        </h2>
        <div className="w-5/6 md:w-[550px] h-14 mt-5 rounded-full gradient-red p-[3px]">
          <div className="w-full h-full rounded-full flex items-stretch justify-between flex-nowrap">
            <input
              type="text"
              placeholder="e.g. https://www.youtube.com/watch?v=fs-eur71DRA"
              className="w-full text-white text-lg rounded-l-full pl-4 font-normal focus:outline-none placeholder:italic placeholder:text-light-red bg-dark-red focus:medium-red hover:medium-red duration-500"
              onChange={(e) => setLink(e.target.value.trim())}
              onKeyDown={(e) => {
                if (e.key == "Enter") {
                  getVideo();
                }
              }}
            />
            <button
              className="w-14 text-2xl hover:w-20 duration-500 flex justify-center items-center rounded-r-full bg-[#B93437] text-white font-medium"
              onClick={getVideo}
              name="Search"
            >
              <ImSearch />
            </button>
          </div>
        </div>
        <div
          className={
            "w-full mt-10 grid md:grid-cols-2 md:grid-rows-1 gap-10 duration-500 ease-in-out " +
            (!loading && !(video && audio && metadata)
              ? "max-h-0 overflow-y-hidden"
              : "max-h-[1000px]")
          }
        >
          <div className="w-full p-2 gradient-red">
            <div className="w-full h-full bg-dark-red p-5">
              <h3 className="text-2xl font-bold text-white">
                {metadata?.title}
              </h3>
              <div className="h-1 w-20 bg-white opacity-50 my-4"></div>
              <ul className="text-lg text-white">
                <li className="flex">
                  Channel:
                  <a
                    href={
                      "https://www.youtube.com/channel/" + metadata?.channelId
                    }
                    className="ml-1 text-lg text-light-red underline flex items-center justify-start"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    {metadata?.author}
                    <ImNewTab className="inline-block ml-1 mb-1" />
                  </a>
                </li>
                <li>
                  Views:{" "}
                  <span className="text-light-red">{metadata?.viewCount}</span>
                </li>
                <li>
                  Duration:{" "}
                  <span className="text-light-red">
                    {parseSeconds(metadata?.lengthSeconds)}
                  </span>
                </li>
                <li>
                  Video quality:{" "}
                  <select
                    className="text-light-red rounded p-2 bg-dark-red"
                    onChange={(e) => {
                      setVideo(null);
                      setQuality(e.target.value);
                      setUpdateVideo(updateVideo + 1);
                    }}
                  >
                    {allFormats?.map((format: any, index: number) => {
                      if (
                        format.mimeType.includes("video/mp4") &&
                        !qualities.includes(format.quality)
                      ) {
                        qualities.push(format.quality);
                        return (
                          <option key={index} className="p-1">
                            {format.qualityLabel}
                          </option>
                        );
                      }
                    })}
                  </select>
                </li>
              </ul>
            </div>
          </div>
          <div className="w-full">
            {video && (
              <div className="flex flex-col mb-7">
                <h4 className="text-2xl font-semibold text-white mb-1">
                  MP4 Video ({video.width}x{video.height})
                </h4>
                <div className="p-2 gradient-red">
                  <video controls className="w-full h-full">
                    <source src={video.url} type="video/mp4" />
                  </video>
                </div>
              </div>
            )}
            {audio && (
              <div className="flex flex-col">
                <h4 className="text-2xl font-semibold text-white mb-1">
                  M4A Audio
                </h4>
                <div className="p-2 gradient-red rounded-full">
                  <audio controls className="w-full">
                    <source src={audio.url} type="audio/mp4" />
                  </audio>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
