import Head from "next/head";
import { useState } from "react";
import { Inter } from "@next/font/google";
import { ImSearch } from "react-icons/im";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [link, setLink] = useState("");
  const [metadata, setMetadata] = useState<any>(null);
  const [video, setVideo] = useState<any>(null);
  const [audio, setAudio] = useState<any>(null);

  const getVideo = () => {
    console.log("fetching", link);
    fetch("/api/getVideo", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ url: link }),
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        const metadata = data.response.videoDetails;
        const video = data.response.streamingData.formats[0];
        const audio = data.response.streamingData.adaptiveFormats.find(
          (format: any) => {
            return format.mimeType.includes("audio/mp4");
          }
        );
        console.log("metadata", metadata);
        console.log("video", video);
        console.log("audio", audio);

        setMetadata(metadata);
        setVideo(video);
        setAudio(audio);
      })
      .catch((err) => {
        console.log("error", err);
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex flex-col items-center justify-center">
        <h1 className="text-6xl font-bold text-red-400">YouTube Downloader</h1>
        <h2 className="text-2xl font-bold text-red-400">
          Download any YouTube video in video (mp4) or audio (m4a) format!
        </h2>
        <div className="w-5/6 md:w-[550px] h-14 mt-5 rounded-full gradient-purple p-[3px]">
          <div className="w-full h-full rounded-full flex items-stretch justify-between flex-nowrap">
            <input
              type="text"
              placeholder="e.g. https://musescore.com/user/34214067"
              className="w-full text-gray-800 rounded-l-full pl-4 font-normal focus:outline-none placeholder:italic bg-indigo-100 focus:bg-white hover:bg-white duration-500"
              onChange={(e) => setLink(e.target.value.trim())}
              onKeyDown={(e) => {
                if (e.key == "Enter") {
                  getVideo();
                }
              }}
            />
            <button
              className="w-14 text-3xl hover:w-20 duration-500 flex justify-center items-center rounded-r-full bg-[#7C75CF] text-white font-medium"
              onClick={getVideo}
              name="Search"
            >
              <ImSearch />
            </button>
          </div>
          {video && (
            <video controls>
              <source src={video.url} type="video/mp4" />
            </video>
          )}
          {audio && (
            <audio controls>
              <source src={audio.url} type="audio/mp4" />
            </audio>
          )}
        </div>
      </main>
    </>
  );
}
